apiVersion: apps/v1beta1 # for versions >= 1.8.0 use apps/v1beta2
kind: Deployment
metadata:
  name: payee-webapp
  labels:
    app: payee-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payee-webapp
  template:
    metadata:
      labels:
        app: payee-webapp
    spec:
      containers:
      - name: payee-webapp
        image: us.gcr.io/payee-183417/payee:v1.0.146.2
        command: ["newrelic-admin"]
        args: [
          "run-program",
          "gunicorn",
          "--workers",
          "$(GUNICORN_WORKERS)",
          "--access-logfile",
          "/dev/stdout",
          "--error-logfile",
          "/dev/stderr",
          "--bind=0.0.0.0:$(PORT)",
          "--timeout=100",
          "--graceful-timeout=120",
          "payee.wsgi"
        ]
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "payee.settings.deploy"
        - name: DEBUG
          value: "0"
        # Gunicorn Settings
        - name: GUNICORN_WORKERS
          value: "8"
        - name: PORT
          value: "8000"
        # Other Settings
        - name: BACKEND_URL
          value: "https://payee.mx/"
        - name: RAVEN_SENTRY_URL
          value: "https://022f95161870462ab971a43a49cfd432:1f4796aa8c6647729cddc7b9480bb851@sentry.io/189968"
        - name: MAIN_DB_HOST
          value: 127.0.0.1
        - name: MAIN_DB_PORT
          value: "5432"
        - name: MAIN_DB_NAME
          value: "payee"
        - name: MAIN_DB_USER
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-deploy-credentials
              key: username
        - name: MAIN_DB_PASS
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-deploy-credentials
              key: password
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                  "-instances=payee-183417:us-central1:payee-main=tcp:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
          - name: ssl-certs
            mountPath: /etc/ssl/certs
          - name: cloudsql
            mountPath: /cloudsql
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: cloudsql
          emptyDir:
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
---
kind: Service
apiVersion: v1
metadata:
  name: payee-webapp
spec:
  selector:
    app: payee-webapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  sessionAffinity: None
  type: LoadBalancer