# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedproduct',
            name='unit',
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Unit'),
            preserve_default=False,
        ),
    ]
